name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: sudo apt update && sudo apt install -y apktool
      - run: apktool b . -o app.apk
      - uses: actions/upload-artifact@v4
        with:
          name: SmartYe-Browser
          path: app.apk
